version: '3.8'

services:
  # Neon Local Database Proxy
  neon-local:
    image: neondatabase/neon_local:latest
    container_name: acquisition-neon-local
    ports:
      - '5432:5432'
    env_file:
      - .env.development
    volumes:
      - ./.neon_local/:/tmp/.neon_local
      - ./.git/HEAD:/tmp/.git/HEAD:ro
    networks:
      - acquisition-network
    healthcheck:
      test: ["CMD-SHELL", "timeout 2 bash -c '</dev/tcp/localhost/5432' || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 30
      start_period: 120s
    restart: unless-stopped

  # Application Service
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    container_name: acquisition-app-dev
    ports:
      - '3000:3000'
    env_file:
      - .env.development
    environment:
      - PORT=3000
      - NODE_ENV=development
    volumes:
      - ./src:/app/src:delegated
      - ./package.json:/app/package.json:ro
      - ./package-lock.json:/app/package-lock.json:ro
      - /app/node_modules
    networks:
      - acquisition-network
    depends_on:
      neon-local:
        condition: service_healthy
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:3000/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  acquisition-network:
    driver: bridge
